# Generated by Django 5.0.6 on 2024-07-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
