# Generated by Django 5.0.6 on 2024-07-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_last_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='defaultusername', max_length=100, unique=True),
        ),
    ]
