"""
Django settings for dernSol project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6jw_rrd9v)w4aroxl51*+_k!ugi82!*ri31gvnz7qy1_g4@%-5"
# SECRET_KEY = os.getenv('django-insecure-463n@eid_+zub+wy2bb6hc!om_j$o4wuy4!7s=9dzo%hx&*h)^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ['derniersoleil.com', 'www.derniersoleil.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "chat.apps.ChatConfig"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'chat.middleware.AutoLoginMiddleware', # Voir > "H:\derSol\01_Archiv_derSol\01_chat_construction\2_Eviter la connexio avec un Middleware.html"

]

ROOT_URLCONF = 'dernSol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dernSol.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
NB:
N'oubliez pas que les paramètres des environnements de développement et de production 
doivent être séparés. Ce code semble plus adapté à l'environnement de développement. 
N'oubliez pas non plus d'exclure les données sensibles du contrôle de version en 
utilisant des variables d'environnement ou des fichiers de configuration externes.
================================================================================
Définissez une variable d'environnement nommée DJANGO_SECRET_KEY avec une valeur unique et imprévisible. Vous pouvez le faire dans les paramètres des variables d'environnement de votre système d'exploitation ou dans le script de profil de votre shell.
Dans votre fichier de paramètres Django, utilisez la fonction os.getenv() pour obtenir la valeur de la variable d'environnement DJANGO_SECRET_KEY, comme ceci :

import os

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
Enregistrez vos modifications et redémarrez votre serveur de développement Django.
Rappelez-vous, la variable SECRET_KEY doit être gardée secrète et ne pas être partagée publiquement. Il est également recommandé d'utiliser des valeurs SECRET_KEY différentes pour les environnements de développement et de production.
"""